[build]
  publish = "public"
  command = "hugo -b $DEPLOY_PRIME_URL --minify"

[context.production.environment]
  HUGO_VERSION = "0.58.3"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --minify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.58.3"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --minify"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.58.3"
